"""numbering

Revision ID: da18ab258def
Revises: 62108649b9c8
Create Date: 2026-09-23 09:03:28.674252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da18ab258def'
down_revision: Union[str, Sequence[str], None] = '62108649b9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_counter',
    sa.Column('resolved_prefix', sa.String(length=400), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('resolved_prefix')
    )
    op.create_table('code_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('prefix_template', sa.String(length=300), nullable=False),
    sa.Column('suffix_template', sa.String(length=100), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('pad_width', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_rule')
    op.drop_table('code_counter')
    # ### end Alembic commands ###
