"""assets and events

Revision ID: ff2d24d960b8
Revises: da18ab258def
Create Date: 2026-09-23 09:15:54.364526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2d24d960b8'
down_revision: Union[str, Sequence[str], None] = 'da18ab258def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_code', sa.String(length=200), nullable=False),
    sa.Column('legacy_asset_code', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('cost_center_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('subcategory_id', sa.BigInteger(), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('pi_number', sa.String(length=100), nullable=True),
    sa.Column('pi_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('warranty_upto', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_holder_id', sa.BigInteger(), nullable=False),
    sa.Column('status_since', sa.Date(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['asset_category.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_center.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['holder.id'], ),
    sa.ForeignKeyConstraint(['current_holder_id'], ['holder.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['asset_subcategory.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['holder.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code')
    )
    op.create_table('asset_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_holder_id', sa.BigInteger(), nullable=True),
    sa.Column('to_holder_id', sa.BigInteger(), nullable=True),
    sa.Column('status_after', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('recorded_by', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['from_holder_id'], ['holder.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['holder.id'], ),
    sa.ForeignKeyConstraint(['to_holder_id'], ['holder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Ledger-protection triggers (spec: asset_event is an append-only audit ledger;
    # asset.asset_code/company_id/cost_center_id are permanent once set). Enforced
    # in the DB itself, not just application code, so direct SQL access can't
    # bypass it either.
    op.execute("""
        CREATE OR REPLACE FUNCTION forbid_asset_event_write() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'asset_event rows are append-only; insert a CORRECTION event instead';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_asset_event_no_update
        BEFORE UPDATE ON asset_event
        FOR EACH ROW EXECUTE FUNCTION forbid_asset_event_write();
    """)
    op.execute("""
        CREATE TRIGGER trg_asset_event_no_delete
        BEFORE DELETE ON asset_event
        FOR EACH ROW EXECUTE FUNCTION forbid_asset_event_write();
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION forbid_asset_identity_change() RETURNS trigger AS $$
        BEGIN
            IF NEW.asset_code IS DISTINCT FROM OLD.asset_code THEN
                RAISE EXCEPTION 'asset_code is immutable once set';
            END IF;
            IF NEW.company_id IS DISTINCT FROM OLD.company_id THEN
                RAISE EXCEPTION 'company_id is immutable once set';
            END IF;
            IF NEW.cost_center_id IS DISTINCT FROM OLD.cost_center_id THEN
                RAISE EXCEPTION 'cost_center_id is immutable once set';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_asset_no_identity_change
        BEFORE UPDATE ON asset
        FOR EACH ROW EXECUTE FUNCTION forbid_asset_identity_change();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_asset_no_identity_change ON asset;")
    op.execute("DROP FUNCTION IF EXISTS forbid_asset_identity_change;")
    op.execute("DROP TRIGGER IF EXISTS trg_asset_event_no_delete ON asset_event;")
    op.execute("DROP TRIGGER IF EXISTS trg_asset_event_no_update ON asset_event;")
    op.execute("DROP FUNCTION IF EXISTS forbid_asset_event_write;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_event')
    op.drop_table('asset')
    # ### end Alembic commands ###
